Reading tests in testdata
It does not run using go test. It outputs:

\# github.com/gonzalez-nunez-uriel/w100 [github.com/gonzalez-nunez-uriel/w100.test]
./main_test.go:21:12: undefined: nill
FAIL	github.com/gonzalez-nunez-uriel/w100 [build failed]

It makes sense, since I have not defined the function to test.
Do I need to run go build to build the test?
No running go build outputs:

github.com/gonzalez-nunez-uriel/w100: no non-test Go files in /home/haramil/Projects/w100